name: CI

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Run code quality checks (Linting, Formatting Check, Type Check, Pre-commit hooks)
        run: make check-all

      - name: Run tests with coverage
        run: make test-cov

  train-model:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Download and preprocess data
        run: |
          python src/load_data.py
          python src/split_dataset.py --test_size 0.2

      - name: Train the model
        run: python src/train.py

      - name: Upload trained model artifact
        uses: actions/upload-artifact@v4
        with:
          name: iris-model
          path: models/model.joblib

  evaluate-model:
    needs: train-model
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          make install

      - name: Download trained model artifact
        uses: actions/download-artifact@v4
        with:
          name: iris-model
          path: models/

      - name: Check that model file exists
        run: |
          if [ ! -f models/model.joblib ]; then
            echo "Model file not found!"
            exit 1
          fi

      - name: Run evaluation script
        run: python src/evaluate.py

      - name: Upload evaluation metrics
        uses: actions/upload-artifact@v4
        with:
          name: evaluation-metrics
          path: data/eval.json
